version: "3"
services:
  sandboardgames:
    container_name: sandboardgames
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: ['8080:8080'] 
    restart: unless-stopped