version: "3"
services:
  sandboardgames:
    container_name: sandboardgames
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: 
      - '8080:8080'
      - '3478:3478/udp'
      - '49152-49252:49152-49252'
    env_file:
      - .env
    restart: unless-stopped