version: "3"
services:
  sandboardgames:
    container_name: sandboardgames
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    network_mode: "host"
    env_file:
      - .env
    restart: unless-stopped